### ISSUE TITLE
TypeError: null is not an object (evaluating 'IntercomEventEmitter.UNREAD_COUNT_CHANGE_NOTIFICATION')

### ISSUE THREAD

**Issue by Chris-Beckett** [cmaycumber/config-plugin-react-native-intercom#6] opened 2022-02-02 11:42 UTC
I'm currently trying to include the carousel from intercom and i'm getting the intercomEventEmitter issue. I'm using Expo to build the React Native application.

```
"expo": "~43.0.0",
"@intercom/intercom-react-native": "^2.0.1",
"config-plugin-react-native-intercom": "^1.0.0"
```

**Code i've tried running:**

```
import Intercom from '@intercom/intercom-react-native';
```

```
React.useEffect(() => {   
  Intercom.displayCarousel('23434117');
}, []);
```

**Error:**

> TypeError: null is not an object (evaluating 'IntercomEventEmitter.UNREAD_COUNT_CHANGE_NOTIFICATION')
> at node_modules\react-native\Libraries\LogBox\LogBox.js:149:8 in registerError
> at node_modules\react-native\Libraries\LogBox\LogBox.js:60:8 in errorImpl
> at node_modules\react-native\Libraries\LogBox\LogBox.js:34:4 in console.error
> at node_modules\expo\build\environment\react-native-logs.fx.js:27:4 in error
> at node_modules\react-native\Libraries\Core\ExceptionsManager.js:104:6 in reportException
> at node_modules\react-native\Libraries\Core\ExceptionsManager.js:172:19 in handleException
> at node_modules\react-native\Libraries\Core\setUpErrorHandling.js:24:6 in handleError
> at node_modules\@react-native\polyfills\error-guard.js:49:36 in ErrorUtils.reportFatalError
> at node_modules\metro-runtime\src\polyfills\require.js:204:6 in guardedLoadModule
> at http://192.168.0.72:19000/index.bundle?platform=android&dev=true&hot=false&minify=false:343612:3 in global code

**Comment by cmaycumber** [comment] 2022-02-15 14:22
I personally haven't tried the displayCarousel method. I'm using `Intercom.displayMessenger();`. Do you know if these work separately? 

Do you think it could be related to this in Intercoms docs?

```
Make sure your carousel is live

A carousel must be ‘live’ to be used in this feature. If it is in a draft or paused state, end-users will see an error if the app tries to open the content.
```
https://developers.intercom.com/installing-intercom/docs/react-native-configuration

**Comment by Chris-Beckett** [comment] 2022-02-15 14:59
Hey @cmaycumber 

I've tried all the different methods such as `Intercom.displayMessenger();` and it's just throwing up 

```
(evaluating 'IntercomEventEmitter.UNREAD_COUNT_CHANGE_NOTIFICATION')
```

**Comment by cmaycumber** [comment] 2022-02-15 15:03
```
I'm using Expo without ejecting to iOS and Android and running it through the metro build. Could this be the issue?
```

So a totally managed build? Or are you using the config plugins? Before building the iOS or Android application make sure to run `expo prebuild`

**Comment by cmaycumber** [comment] 2022-02-15 15:06
I'm pinned at `"@intercom/intercom-react-native": "1.1.1",` and on expo v44.

**Comment by Chris-Beckett** [comment] 2022-02-16 10:28
My steps are to do 

`npm run android` and it boots up metro and runs through the expo application while testing. Then to test standalone i'm running `expo build:android --release-channel="development"`

**Comment by Chris-Beckett** [comment] 2022-03-15 09:24
@cmaycumber You got any updates on what this could be?

**Comment by cmaycumber** [comment] 2022-03-15 13:35
@Chris-Beckett I'll try to see if I can get to the bottom of this somehow. Would it be possible for you to clone this repo and try running the example app?

**Comment by cmaycumber** [comment] 2022-03-15 17:31
@koukoujohn From my understanding, this happens when `@intercom/intercom-react-native` doesn't link properly. Is it possible to share your versions? 

I'd try to see if running the example app fixes this. But I'll have some time to look into this some more tonight.

**Comment by koukoujohn** [comment] 2022-03-15 17:51
This is what I get by running eas diagnostics on my environment:
---------------------------------------------------------------------------

EAS CLI 0.48.0 environment info:
    System:
      OS: Windows 10 10.0.19044
    Binaries:
      Node: 14.17.6 - C:\Program Files\nodejs\node.EXE
      npm: 6.14.15 - C:\Program Files\nodejs\npm.CMD  
    Utilities:
      Git: 2.33.0. - /mingw64/bin/git
    npmPackages:
      expo: ^44.0.6 => 44.0.6
      expo-dev-client: ~0.8.4 => 0.8.4
      expo-updates: ~0.11.6 => 0.11.6
      react: 17.0.1 => 17.0.1
      react-dom: 17.0.1 => 17.0.1
      react-native: 0.64.3 => 0.64.3
      react-navigation: ^4.4.4 => 4.4.4
    Project workflow: managed

This is intercom related packages in my dependencies in package.json:
-------------------------------------------------------------------------------

"@intercom/intercom-react-native": "^2.1.0"
"config-plugin-react-native-intercom": "^1.2.0"

And this is what expo installs on their servers during spinning up build environment stage:
------------------------------------------------------------------------------------------------------
- Xcode 13.0 (13A233)
- Node.js 16.13.2
- Yarn 1.22.17
- npm 8.1.2
- fastlane 2.185.1
- CocoaPods 1.10.1
- Ruby 2.7.0p0 (2019-12-25 revision 647ee6f091) [x86_64-darwin19]

This is the config Plugin in my app.json
-------------------------------------------
  [
    "config-plugin-react-native-intercom",
    {
      "iosApiKey": "private",
      "androidApiKey": "private",
      "appId": "private",
      "experimentalBumpMinIosPlatformVersion": true,
      "iosPhotoUsageDescription": "Upload images to support center"
    }
  ]

Thanks in advance @cmaycumber

**Comment by koukoujohn** [comment] 2022-03-16 09:53
Unfortunately I couldn't build the example app. 

In android during gradlew stage I got this fail error:

xecution failed for task ':expo-updates:kaptDebugKotlin'.
[stderr] > A failure occurred while executing org.jetbrains.kotlin.gradle.internal.KaptExecution
[stderr]    > java.lang.reflect.InvocationTargetException (no error message)

And in iOS I didn't have access make a new adhoc app right now, I'm looking into it.

But two things I noticed are these differences between the versions and dependencies in the example app and my app.

- I didnt have react-native-web as a dependency.
- I didn't have luxon as a dependency.
- I didn't have i18n-js as a dependency.
- I didn't have expo-status-bar as a dependency.
- My expo version is 44.0.6 and in the example is 44.0.0
- My "@intercom/intercom-react-native" version is 2.1.0 and in the example it's 2.0.3

I know some of these are irrelevant but I want to be thorough between the version differences

**Comment by cmaycumber** [comment] 2022-03-16 16:01
> I know some of these are irrelevant but I want to be thorough between the version differences

Thanks, I'll try a totally fresh repo. To see if I can reproduce this.

**Comment by cmaycumber** [comment] 2022-03-17 13:18
@koukoujohn mentioned that this issue was fixed for him in the latest version after an `expo prebuild`, can you give this a shot? @Chris-Beckett

**Comment by koukoujohn** [comment] 2022-03-17 13:51
@cmaycumber It works on Android expo dev client (therefore also for Android production). It still insists on iOS.

I think I pinpointed the reason for this message on my iOS though!

What was happening and I just realised today, is that with eas build --platform ios the app was building just fine,
but when I was installing it through ios adhoc the installation was silently failing.

It wasn't showing any message on my iOS device why it failed and because I wasn't checking the phone at the moment I didn't notice it failed.

Then I opened the iOS expo dev client loaded the app as usual but the app that I was actually seeing was my previous version. Which didnt have intercom related packages installed! So it's normal I was getting the crash and the message.

Its not an issue with my ios credentials or adhoc setup for my device because when I remove the two dependencies
"@intercom/intercom-react-native": "^2.1.0"
"config-plugin-react-native-intercom": "^1.2.0"

the app can be installed again succesfully!

I will try to make builds with one of these dependencies removed independently to see which one of them causes the installation issue.

There is a high chance everyone here is having the same issue with me, but I'm not completely sure yet.

I will let you know

**Comment by Chris-Beckett** [comment] 2022-03-18 10:54
@cmaycumber I've got it working with the pre-build and building the android/ios folders. 

I would trying to run without building etc and trying to use the simple "npm run android" when you first set up expo. 

However when trying to use `Intercom.displayMessager()`  - every time it opens, it says "Something went wrong, give it another try"

**Comment by cmaycumber** [comment] 2022-03-18 13:54
> @cmaycumber @koukoujohn How are you guys dealing with the registering user part, have you made some sort of hook to only run once on app start up?

I can share some of the code we're using. But that's really up to you on whether you want to register unidentified or identified users when they login. Like you said early you should only have to run this once but you can run it every time the user opens the app, I don't think intercom is picky about that.

**Comment by Chris-Beckett** [comment] 2022-03-18 14:48
> > @cmaycumber @koukoujohn How are you guys dealing with the registering user part, have you made some sort of hook to only run once on app start up?
> 
> I can share some of the code we're using. But that's really up to you on whether you want to register unidentified or identified users when they login. Like you said early you should only have to run this once but you can run it every time the user opens the app, I don't think intercom is picky about that.

That would be awesome, if you could share some code. I would love to see how you've structured it compared to how I'm going to structure it.

**Comment by koukoujohn** [comment] 2022-03-18 21:19
@Chris-Beckett sorry I didn't come across this issue. Does it stop fastlane and fail the build?

I will try to build iOS again to check if I get it. It might be something wrong in the expo side.

Im guessing you are trying to build with EAS servers with a managed workflow right? Else try deleting package-lock and node-modules and re-installing(actually try this anyway)

About the Intercom register, yes they dont mind what method you use. It depends if you want to collect information about the user in their platform.

We register and update the users each time they finish the authentication/sign-up process. Intercom doesnt care how many times you register them. We dont register unidentified/ logged out users and we dont show intercom to them. But that's our choice.

**Comment by Chris-Beckett** [comment] 2022-03-18 22:26
> @Chris-Beckett sorry I didn't come across this issue. Does it stop fastlane and fail the build?
> 
> I will try to build iOS again to check if I get it. It might be something wrong in the expo side.
> 
> Im guessing you are trying to build with EAS servers with a managed workflow right? Else try deleting package-lock and node-modules and re-installing(actually try this anyway)
> 
> About the Intercom register, yes they dont mind what method you use. It depends if you want to collect information about the user in their platform.
> 
> We register and update the users each time they finish the authentication/sign-up process. Intercom doesnt care how many times you register them. We dont register unidentified/ logged out users and we dont show intercom to them. But that's our choice.

I think there is a problem with my build anyway, it works in development client but soon as I try and build with EAS it crashes on trying to load the application and not sure what the best way is to try and debug as it runs fine every time building straight to device with development client.

**Comment by cmaycumber** [comment] 2022-03-21 13:24
> EAS it crashes on trying to load the application and not sure what the best way is to try and debug as it runs fine every time building straight to device with development client.

You can give flipper a shot: https://fbflipper.com/docs/features/react-native/. Also, another way to debug crashes on startup is through either `abd` for android, there's also one for iOS but can't think of it off the top of my head.

**Comment by koukoujohn** [comment] 2022-03-23 21:44
@Chris-Beckett sorry for the late response

Sure my discord handle is koukoujohn text me when you can, but I have to say that for react native debugging I only have knowledge of reactotron as a debugging tool. I haven't used other debugging tools yet. I hear good things about flipper too and that it's a rising star!

**Comment by Chris-Beckett** [comment] 2022-03-24 12:23
> koukoujohn

Thanks I will try reactotron and flipper to see what I can resolve :) - Hopefully have intercom working on my app very soon :) 

I couldn't find you on discord as i need the # numbers aswell. 

Mine is ChrisssyyyB#2477 - if you want to ping me a message.

**Comment by Chris-Beckett** [comment] 2022-03-30 12:36
@cmaycumber @koukoujohn  - I've got the app working without the crashing, however it's calling all the intercom methods fine and I'm getting `true` on the promise response from like `displayMessager()`. However the messager isn't poping up, it's doing nothing. 

Any ideas?

**Comment by cmaycumber** [comment] 2022-04-11 13:32
@Chris-Beckett Are you able to provide any logs or anything?

**Comment by koukoujohn** [comment] 2022-04-27 07:55
@Chris-Beckett sorry I didn't do something else other what's in the instructions of @cmaycumber and the instructions in intercom's site for react native developers! When I used the displayMessenger() it worked. Make sure you have a paying account with intercom and that you have followed all of their instructions(register users when authentication flow finishes etc.). I also am using intercom react native version 2.0.4 because expo doesn't target Android API 31 yet, so I can't use version 2.1.0 and up yet.

**Comment by cmaycumber** [comment] 2022-05-11 01:47
Going to close this for now feel free to comment on the issue if you still have problems!

**Closed by cmaycumber** 2022-05-11 01:47 UTC
